import React from "react";
import Image from "next/image";
import bgimage from "@/public/images/Section-3-Background.jpg";
import phone from "@/public/images/Phone-932x1024.png";

const TradingBotB = () => {
  return (
    <div className="flex justify-center items-center mt-32 px-48 w-full">
      <div className="flex flex-row justify-center items-center w-full space-x-10">
        {/* Left Side */}
        <div className="flex flex-col space-y-10 w-1/2">
          <div className="text-4xl font-semibold leading-normal">
            Fast-track your crypto
            <br /> success
          </div>
          <div className="leading-6 font-light text-sm tracking-wide">
            Watch This Video & See For Yourself Why EazyBot Is
            <br />
            Hands-Down The Easiest & Painless Way To Trade Crypto
          </div>
          <div className="flex justify-start items-center">
            <button className="text-white leading-6 font-basex bg-hcolor text-sm tracking-wide px-12 py-3 rounded-full shadow-2xl shadow-hcolor">
              Learn more
            </button>
          </div>
        </div>

        {/* Right Side - Video with Background */}
        <div className="relative w-1/2">
          {/* Background Image */}
          <div
            className="absolute inset-0 bg-cover bg-center rounded-lg"
            style={{
              backgroundImage:
                "url('https://i.vimeocdn.com/video/1444088858-994565a96c9851f5ce7a7fa8dec3040d3bcd7a5a7fdc307758652ceac9b1f993-d?mw=800&mh=449&q=70')",
            }}
          ></div>

          {/* Video */}
          <video
            className="relative z-10 rounded-lg w-full h-auto"
            controls
            preload="none"
            src="blob:https://player.vimeo.com/4aea621e-8d1e-4223-b90a-1b9e6f1bbce0"
          >
            <track
              kind="captions"
              src="/texttrack/21750513.vtt?token=66c70e95_0x7c10a6bb3d11db8079340ddc53dc86b7b33f1f08"
              srcLang="en-x-autogenerated"
              label="English (auto-generated)"
            />
          </video>
        </div>
      </div>
    </div>
  );
};

const TradingBotB = () => {
  return (
    <div className="flex justify-center items-center mt-32 px-48 border-2 border-black w-full">
      <div className="flex flex-row justify-center items-center border-2 border-black w-full">
        <div className="flex flex-col space-y-10 border-2 border-black w-full">
          <div className="text-4xl font-semibold leading-normal">
            Fast-track your crypto
            <br /> success
          </div>
          <div className="leading-6 font-light text-sm tracking-wide">
            Watch This Video & See For Yourself Why EazyBot Is
            <br />
            Hands-Down The Easiest & Painless Way To Trade Crypto
          </div>
          <div className="flex justify-start items-center">
            <button className=" text-white leading-6 font-basex bg-hcolor text-sm tracking-wide px-12 py-3 rounded-full shadow-2xl shadow-hcolor">
              Learn more
            </button>
          </div>
        </div>
        <div className="border-2 border-black w-full"></div>
      </div>
    </div>
  );
};

const VideoWrapper = () => {
  return (
    <div
      className="vp-video-wrapper transparent content-area-sibling-enabled"
      aria-hidden="true"
    >
      <div className="vp-video">
        <div className="vp-telecine invisible vp-telecine-cover">
          <video
            preload="none"
            tabIndex="-1"
            src="blob:https://player.vimeo.com/4aea621e-8d1e-4223-b90a-1b9e6f1bbce0"
          >
            <track
              kind="captions"
              src="/texttrack/21750513.vtt?token=66c70e95_0x7c10a6bb3d11db8079340ddc53dc86b7b33f1f08"
              id="telecine-track-21750513"
              srclang="en-x-autogenerated"
              label="English (auto-generated)"
            />
          </video>
        </div>
      </div>
      <div
        className="vp-preview vp-preview-cover"
        id="vp-preview"
        style={{
          backgroundImage: `url("https://i.vimeocdn.com/video/1444088858-994565a96c9851f5ce7a7fa8dec3040d3bcd7a5a7fdc307758652ceac9b1f993-d?mw=800&mh=449&q=70")`,
        }}
      />
    </div>
  );
};
